Cleans Up Folder Hiearchy
tythonco/tython-website pull request #10
Opened 2021-03-08 15:31 UTC by scottbcovert

This PR:
- Cleans up folder hierarchy (categories can be used to autogenerate the same permalinks that nested folders would)
- Adds new draft npm script
- Updates README
- Adds `layout` frontmatter to all posts/drafts
- Adds `--future` tag to test npm script so future-dated drafts will be previewed locally

2021-03-08 15:32 UTC, scottbcovert commented on README.md
> +2. `npm run draft "My New Post"`
This will automatically create `my-new-post.md` within the `_drafts` folder with a title of `My New Post` in its frontmatter along with other, empty frontmatter details to be filled in by the author

2021-03-08 15:34 UTC, scottbcovert commented on README.md
> +2. After the PR has been merged, our scheduled
Truthfully I'm getting ahead of myself here b/c this hasn't been set up yet, but this is the soon-to-be state 👍

This action crawls the `_drafts` folder and finds any drafts with a `date` set in the past, prepends the filename with the current date (as is necessary for true posts), and moves it to the `_posts` folder before pushing a new commit that triggers a site rebuild ⚙️

2021-03-08 15:35 UTC, scottbcovert commented on README.md
> +[Jekyll CheatSheet](https://devhints.io/jekyll)
Came across this and thought it could be useful down the road, specifically the `_layouts` and `_partials` information, which can be used for future styling and templating (such as a footer with a CTA 👍 )

2021-03-08 21:28 UTC, ndrewr commented on README.md
We may need to add some "Setup" instructions at the top for development environment.
For one, to specify that `Ruby` and the `bundler` gem need to be installed for the npm scripts (and Jekyll) to work.

2021-03-08 21:33 UTC, ndrewr commented on package.json
> +    "test": "bundle install && open http://localhost:4000 && bundle exec jekyll serve --livereload --drafts --future"
As mentioned above, the `bundle` command requires Ruby to be installed as well as the gem `bundler`. I believe thats pre-installed on macs, but I found it wasn't on my system.

The `open` command is also seemingly mac-specific? I think its analogous to `xdg-open`?

[Stack post on the command](https://unix.stackexchange.com/questions/253376/open-command-to-open-a-file-in-an-application#:~:text=On%20some%20Linux%20distributions%20the,in%20a%20new%20virtual%20console.&text=html%20should%20open%20the%20file,browser%2C%20xdg%2Dopen%20image.)

I can set up the alias or a function on my system no prob, but if there is a x-platform command we could use instead that would be more future-proof for other devs.

2021-03-08 21:55 UTC, ndrewr requested changes
After sorting out my dev environment (had to install Ruby) `npm test` command works 👍 
Livereload doesn't seem to work for me, but I am assuming thats a problem with my setup so I'll investigate separately.

I do think we should update the README with basic Setup/Dependency section, and also generalize the `open` command used in the `npm test` script.

2021-03-08 22:43 UTC, scottbcovert commented on README.md
Yea, I'm going to try to get Ruby and bundler to install as a preinstall step so that running `npm install` will get you all set up

2021-03-09 02:48 UTC, ndrewr commented on package.json
> +    "preinstall": "gem install bundler jekyll",
Observation: I find the `gem install` cmd requiring `sudo` for me, but I don't know if thats the case for most.
What I had to do was slap `sudo` in there before running the `npm install` command.

2021-03-09 02:51 UTC, scottbcovert commented on package.json
> +    "preinstall": "gem install bundler jekyll",
What about this:

`"preinstall": "gem install --user-install bundler jekyll",`

Does that still require sudo for you?

2021-03-09 02:51 UTC, ndrewr approved these changes
I think it is fine but tbh I think you can do away with the `preinstall` script given the `sudo` inconsistency btwn environments and then just note those in the README section.

2021-03-09 02:51 UTC, scottbcovert commented on package.json
> +    "preinstall": "gem install bundler jekyll",
I pulled the gem install command from Jekyll docs; perhaps it's a bit out of date and there isn't a need to install bundler and jekyll 🤷‍♂️

2021-03-09 02:57 UTC, scottbcovert commented
> I think it is fine but tbh I think you can do away with the `preinstall` script given the `sudo` inconsistency btwn environments and then just note those in the README section.

Agreed, I wonder if the sudo would still be required if the `--user-install` flag were added but I think it's fine to just list it as a pre-req as you suggest

2021-03-09 03:03 UTC, scottbcovert commented
The latest commit auto-dismissed the approval but given it just added requested changes I'm going to go ahead and merge 👍

2021-03-09 03:03 UTC, merged